pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {https://github.com/freebootcamp/simple-node-js-react-npm-app/blob/master/jenkins/Jenkinsfile
            steps {
                sh 'whoami'
            }
        }
    }
}
